### ISSUE TITLE
[Bug]: Breaks Mermaid preview extension support

### ISSUE THREAD

**Issue by bmrussell** [lzm0x219/vscode-markdown-github#203]
### Describe the bug

1. Install bierner.markdown-mermaid
2. Add markdown with in-line mermaid
3. Preview (diagram drawn)
4. Install  vscode-markdown-github
5. Preview (code block is rendered instad of diagram)

### To Reproduce

Use with bierner.markdown-mermaid 

### Expected behavior

Diagram is rendered

## Before
![before](https://github.com/lzm0x219/vscode-markdown-github/assets/7798077/60a4812f-8119-4a6d-ba62-4eff8a5a51b6)

## After
![after](https://github.com/lzm0x219/vscode-markdown-github/assets/7798077/c9aba3bb-27e9-4da8-a56e-49d5b5e8476f)

### Environmental information

Windows 22 2H22

### Additional context

I see mermaid is on your road map for v2, but a fix for this would be nice...

**Comment by lzm0x219** [comment]
Yes, I will add support for this soon.

**Comment by lzm0x219** [comment]
You can uninstall `bierner.markdown-mermaid`, I updated
