### ISSUE TITLE
image of IMG Tag with absolute path can not be displayed

### ISSUE THREAD

**Issue by 9527q** [lzm0x219/vscode-markdown-github#74]
If the image path in the IMG Tag is an absolute path, the image can not be displayed

![image](https://user-images.githubusercontent.com/37435717/209983626-1051f225-4873-4ad0-8afa-0dd10f2f48e0.png)

**Comment by lzm0x219** [comment]
Here are the path rules of VSCode, which are not consistent with github.

**Comment by lzm0x219** [comment]
But i think it can be fixed. soon...
